### ISSUE TITLE
Colors indicating difficulty do not update while profession window is open

### ISSUE THREAD

**Issue by balanthor** [b-morgan/Skillet-Classic#10]
As you craft items, the color indicator for the difficulty doesn't update to reflect the new skill level while the window is open. You have to close the window, and reopen it to force the update.  This in TBC classic

**Comment by b-morgan** [comment]
Noted. This may take a long time to fix as it requires obtaining materials (or gold), crafting a recipe repeatedly until the error occurs, changing the code, and repeating the process until the fix is found. There will probably be profession unlearning and relearning as well to keep material requirements within reason.

**Comment by b-morgan** [comment]
@Dejoule, you would be correct except that you can't unlearn cooking so each experiment involves creating a new character, leveling to 5, learning cooking, leveling spiced bread until it is supposed to change color and if the experiment fails, delete character and start again.

I believe skinning / leatherworking is probably the best combination for this. Each experiment involves unlearning / learning leatherworking, level until color change, and repeat until the bug is discovered and eliminated. As the character gains XP and skinning skill, it will be easier and easier to acquire materials for the experiments.

**Comment by b-morgan** [comment]
Skillet-Classic caches this information when the profession is opened and the cache is used to generate the actual frame.

I'm not sure how much performance impact there will be but the following change can be made to `...\Addons\Skillet\UI\MainFrame.lua` by replacing line 1097 with the two lines below:

```
			local _, difficulty = GetTradeSkillInfo(skillIndex)
			local skill_color = Skillet.skill_style_type[difficulty] or skill.color or skill.skillData.color or NORMAL_FONT_COLOR
```
All I have tested so far is that this change doesn't appear to break anything. I'm still leveling a character to test that it actually works. Please make the change in your local copy and let me know what happens.

**Comment by BurnHavoc** [comment]
Quite a few things seem to not update: the color coding, the number of items craftable, the queue when queuing up things, the queue processing numbers. also if you scroll through a list, select an item, you can then no longer scroll until you either choose a different profession or open/close the skillet window. This isn't the first addon with visual update issues though, as I've seen a couple other addons require closing/reopening or re-highlighting targets to force visual updates. So it seems to be broader problem/change for pre-patch/TBC.

**Comment by b-morgan** [comment]
@BurnHavoc, I tested this color change code using Skillet-Classic on Burning Crusade Classic and none of the things you mention failed to update as I was watching the screen while I created 10 Copper Bars to transition from Orange to Yellow. I also just verified that I can select and scroll (and select a different recipe) without issue on my system.

I believe you have a completely different issue and as such, you should open a new issue. Please include as much detail as possible so that I can figure out what might be wrong. You might want to try with just Skillet-Classic enabled to eliminate any other addon interference.

**Comment by b-morgan** [comment]
This change will be included in the next build.
