### ISSUE TITLE
Process/Pause button

### ISSUE THREAD

**Issue by Raulfin** [b-morgan/Skillet-Classic#106]
The Process button text doesn't hide during a milti-item craft after the first item in the set is crafted. No other mods active that, afaik, mess with crafting except mtsl.
![WowClassic_bG2FhanBzT](https://user-images.githubusercontent.com/7994405/190915592-9ee8da71-095d-4896-93b8-01c735728af4.png)

reproduce: craft 2+ of any item, after the first completes the process text will stay on the button.

**Comment by b-morgan** [comment]
This should be fixed in [Skillet-Classic-1.49-alpha4](https://www.curseforge.com/wow/addons/skillet-classic/files/3995997)

**Comment by Raulfin** [comment]
the button shows pause during the first craft, but after the first craft it shows process instead of pause during subsequent crafts.  seems they just show bacwards after the first craft.

![WowClassic_RnzyFVHr7S](https://user-images.githubusercontent.com/7994405/190938797-f2244578-6ff2-42ea-b567-2cf6bc62783c.png)

**Comment by b-morgan** [comment]
Try [Skillet-Classic-1.49-alpha5](https://www.curseforge.com/wow/addons/skillet-classic/files/3996503)

**Comment by Raulfin** [comment]
still is

**Comment by Raulfin** [comment]
https://user-images.githubusercontent.com/7994405/191053167-087cd964-27bc-4ece-98da-49866869acbc.mp4

**Comment by b-morgan** [comment]
> was also wondering if there was somewhere I could request a feature/change.

Absolutely! Open an issue! You can put "Enhancement" or "Feature Request" in the title. We'll discuss it and then I'll reject it!

Just kidding... all reasonable requests are considered and implemented when appropriate.

**Comment by b-morgan** [comment]
Alright it looks like we have to get serious...
Please type:
```
/skillet debuglogging on
/skillet tabledump
/skillet debuglevel 4
/skillet tracelog on
```
With Skillet-Classic closed:
`/skillet cleardebuglog`
Open Skillet-Classic (it looks like you are using cooking)
Select the test case recipe
Increase count to 3 or 4
Click `Queue`
Click `Process`
When processing is complete, Close Skillet-Classic
Logoff or `/reload`
Zip the character specific saved variables file, Skillet-Classic.lua and post it here.

I'm using First Aid and creating multiple Linen Bandages. When I click `Process` the button changes to `Pause` and remains as `Pause` until the crafting is complete at which time the button changes back to `Process`. If I click `Pause` while crafting is in progress, the crafting stops and the queue contains the recipe with an updated count, the button says `Process` and can be clicked to continue.

Your video clips were semi-useful. The fancy cursor gets in the way and because you have cropped it down so much, the progress bar obscures the button.

**Comment by Raulfin** [comment]
:)
1sec git says doesn't support .7z

**Comment by b-morgan** [comment]
Github can be a bit paranoid at times. Use .zip instead of .7z

I think I forgot to add "Update to the latest Skillet-Classic alpha before testing".

It will either be [Skillet-Classic-1.49-alpha6](https://www.curseforge.com/wow/addons/skillet-classic/files/3996766) or Skillet-Classic-1.49-alpha7 (a work in progress).

**Comment by Raulfin** [comment]
kk just got a6 off curse, 1s

**Comment by Raulfin** [comment]
zip file didn't work either, but the button seemed fine now.

https://www.dropbox.com/s/8xfy4vtx0sk7i1x/Skillet-Classic.7z?dl=0
