### ISSUE TITLE
Enchanting tab missing buttons

### ISSUE THREAD

**Issue by Kelryth** [b-morgan/Skillet-Classic#11]
https://i.postimg.cc/fTNj2M1x/Wo-WScrn-Shot-052921-040659.jpg

The tailoring and cooking tabs look and work fine but as you can see in the image the enchanting tab is missing buttons. 

Versions: 1.23-beta4-bcc, 1.24-alpha-classic  (I tried both) tested with other addons disabled. No error reported.

**Comment by b-morgan** [comment]
This is by design. In Classic and Burning Crusade Classic, there is no enchanting vellum. Once the "Enchant" button is pressed, the enchant needs to target the appropriate piece of gear. The "missing" buttons make no sense.

The "Queue" button (an optional feature) allows missing materials needed to be added to the Shopping List. The Shopping List allows your character, or alts, to gather those materials from the usual places same as the other professions. 

You could argue that this queuing feature (which was added after Enchanting was implemented) could benefit from a count, but creating a special case for the optional feature didn't seem necessary.

**Comment by Kelryth** [comment]
the creation of wands don't work because there is no way to start the creation

**Comment by b-morgan** [comment]
Strange. In Classic and Burning Crusade Classic, Enchanting is not a trade skill, it is a craft. The Blizzard API for crafts is completely different than the API for trade skills. There is only one "action" button in the Blizzard Enchanting UI and it doesn't change based on the recipe selected. 

Same with Skillet-Classic. I just verified that rods and wands are created by collecting the materials and then pressing the Enchant button in the Skillet-Classic frame.

Just FYI, the Skillet-Classic "Enchant" button is actually the Blizzard UI "Enchant" button. Skillet-Classic steals it from the Blizzard UI because the API function DoCraft is protected from being executed outside of the Blizzard UI. Skillet-Classic puts it back if you shift-click the profession to open the Blizzard UI temporarily. I don't remember which expansion switched Enchanting from a craft to a trade skill like all the rest of the professions. Skillet (retail) doesn't have to deal with this foolishness.
