### ISSUE TITLE
Chat linking not working?

### ISSUE THREAD

**Issue by fireboy92k** [b-morgan/Skillet-Classic#12]
Maybe I have another add on blocking something, but using the standard Blizz UI linking works.  When using Skillet it doesn't.  On the TBC build.

**Comment by b-morgan** [comment]
What are you trying to link?

**Comment by fireboy92k** [comment]
anything.  anything I click on doesn't appear in chat.

**Comment by fireboy92k** [comment]
I just unloaded everything BUT skillet as addons and it's still happening.  I also quit, deleted the addon folder and the variables in the WTF directory, and reloaded with just skillet and still same issue.

Also, on SOME items that need others made when I click them where it would normally queue it's not pulling everything correctly and in some cases coming up with really wild values for mats needed.

![Untitled](https://user-images.githubusercontent.com/56378639/120085566-484cdb80-c0a7-11eb-9c45-4fddf174f212.png)

**Comment by b-morgan** [comment]
On my system:
                                                     In the Blizzard UI    In the Skillet-Classic UI 
Shift-LeftClick in recipe list                  Works                   Doesn't work
Shift-LeftClick on Item                         Works                   Works
Shift-LeftClick on reagents                  Works                    Works
Alt-LeftClick on Item                            Doesn't work        Works (links all reagents with quantity)
Ctrl-LeftClick on Item                           Dressing Room     Works

Which of these options doesn't work for you? What other Blizzard UI links don't work in Skillet-Classic?

This issue has the title "Chat linking now working?" so let's address that here. Please open a new issue for the queuing / crafting problem.

**Comment by fireboy92k** [comment]
Sure. I'll split the other one out.

Yes, that looks consistent with what I'm seeing as well.  The recipe one was of course the one I noticed.  :)

**Comment by b-morgan** [comment]
The reason why shift left click doesn't work the same in the recipe list is that you can left click to select one recipe and then shift left click on another and it will select all recipes in between. Ctrl left click can be used to select multiple non-consecutive recipes. While a recipe is (or multiple recipes are) selected, you can right click and do things, part of Skillet-Classics ability to create custom groups of recipes.

For the icons flip flopping, please open a separate issue. One problem per issue makes it easier for myself and others to keep track and it allows me the opportunity to fix one thing at a time and release a build for that fix.

**Comment by fireboy92k** [comment]
Didn't realize you could create your own groups.  LOL  Learn something everyday.  So yes, the hold shift and select a range work as you'd expect them to as does the control and select specific items as well.

Only ones that don't seem to be working for me as you posted above are Shift-Left click posting reciepe link to chat and the alt-left click, which for me is posting nothing.  

Linking for regents and items on shift click does post to chat, as does ctrl left clicking to wear an item.

**Comment by b-morgan** [comment]
In the image below, a ShiftLeftClick on the Runecloth Bag icon followed by an AltLeftClick on the Runecloth Bag produced the say text as shown (the text in square brackets are links).

![ShiftClick-AltClick](https://user-images.githubusercontent.com/1547854/120088314-6406b080-c0ac-11eb-8eec-37096966ee67.jpg)

**Comment by fireboy92k** [comment]
Interesting.  Neither of those are working for me with all my addons loaded or nothing loaded except skillet.

**Comment by b-morgan** [comment]
The attached zip file contains two files which should replace `...\Skillet-Classic\TradeSkillInfo.lua` and `...\Skillet-Classic\UI\MainFrame.lua`. 

The MainFrame.lua contains a recipe list right-click menu item "Link Recipe".

The TradeSkillInfo.lua file adds debug statements to the two functions called by shift left clicking and alt left clicking the RuneCloth Bag icon. To display debugging output, type "/skillet debugshow on" in chat (to turn debugging off, type "/skillet debugshow off"). Obviously, pick your own recipe instead of "Runecloth Bag" :-) and let me know what happens.

[Skillet-Classic.zip](https://github.com/b-morgan/Skillet-Classic/files/6565543/Skillet-Classic.zip)

**Comment by fireboy92k** [comment]
![image](https://user-images.githubusercontent.com/56378639/120091778-3b96aa80-c0dc-11eb-8aa0-52e1ad1688f9.png)

Happened to click on Master Engineer's Goggles on my main who is engineering.

**Comment by fireboy92k** [comment]
Here is a cleaner list.  I loaded an addon to copy from chat:

Skillet-Classic: SkilletShow(), currentTrade= nil
Skillet-Classic: name= 'Leatherworking', rank= 300, maxRank= 300
Skillet-Classic: SkilletShowWindow(), currentTrade= 2108, scanInProgress= nil
Skillet-Classic: RescanTrade(), currentTrade= 2108, lastTrade= nil
Skillet-Classic: ScanTrade: Leatherworking: 2108 148 recipes
Skillet-Classic: ScanTrade: replacing '2108 7284 - -' with '2108 7284 7287:6:2319:4:2321:1 -'
Skillet-Classic: SortAndFilterRecipes(), skillListKey= Todday:2108:Blizzard
Skillet-Classic: ShowTradeSkillWindow()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: ShowTradeSkillWindow complete
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: ShowReagentDetails()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: ShowReagentDetails()
Skillet-Classic: ConfigureRecipeControls()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: ShowReagentDetails()
Skillet-Classic: ConfigureRecipeControls()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: ShowReagentDetails()
Skillet-Classic: ConfigureRecipeControls()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: ShowReagentDetails()
Skillet-Classic: ConfigureRecipeControls()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: ShowReagentDetails()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)
Skillet-Classic: ShowReagentDetails()
Skillet-Classic: UpdateTradeSkillWindow()
Skillet-Classic: UpdateShoppingListWindow(false)

**Comment by b-morgan** [comment]
The Skillet-Classic debugging does two things, it outputs debug statements to chat and it outputs that same data to your character specific saved variables file, Skillet-Classic.lua (`D:\World of Warcraft\_classic_\WTF\Account\BSMORGAN\Azuresong\Gracob\SavedVariables\Skillet-Classic.lua`).

The global saved variables file, Skillet-Classic.lua (`D:\World of Warcraft\_classic_\WTF\Account\BSMORGAN\SavedVariables\Skillet-Classic.lua`), contains the database for all of your characters.

Typing "/skillet debugshow on" turns on both outputs, "/skillet debugshow off" turns off chat but keeps the saved variables logging on. This log has a maximum size and keeps only the most recent output. It can be turned off with "/skillet debuglogging off" but it has a minimal performance impact so I leave it on all the time.

You can zip both files (I rename the per character file so they can both easily be zipped) and attach them here instead of trying to capture the chat output.

Now lets make sure we both understand where to click:

![ShiftClick-AltClick](https://user-images.githubusercontent.com/1547854/120103524-4158b400-c10d-11eb-982d-0b75508878db.jpg)

The blue box is one item in the recipe (left) frame. Click this to load this recipe into the detail (right) frame. The white box is the detail frame icon, the green box is a reagent in the detail frame. the red box is the chat output from shift-clicking in the white box followed by alt-clicking in the white box. If you had shift-clicked the icon in the green box, only "[Bolt of Runecloth]" would have been sent to chat. A left click in the green box would take you to the recipe for a Bolt of Runecloth.

**Comment by fireboy92k** [comment]
Ah, well there you go.  Yes, shift and alt clicking on the icon in the WHITE box does post to chat.  I've used this addon for years and not sure why I never noticed that it was only over there where you clicked to post to chat.  But now knowing that it does work.  

Given that I suspect we can close this.  Apologies again for all the drama and thanks for the help.

**Comment by b-morgan** [comment]
No need to be sorry, we both learned something. The code for a couple of the link options needed some TLC which will appear in the next release. Found similar bugs in Skillet (for retail) as well.
