### ISSUE TITLE
[Enhancement] Filter by Xpac option request

### ISSUE THREAD

**Issue by joltox** [b-morgan/Skillet-Classic#122]
Just wondering if its possible to create a filter per expansion?

**Comment by joltox** [comment]
Yeah I mean as in recipes, patterns, and enchants that are available per expansion of the game. Via a drop down menu Similar to how retail base version works. 
Vanilla wow (old world)
Tbc
wrath

**Comment by b-morgan** [comment]
The Blizzard API functions return a count (GetNumTradeSkills) and a list of headers, subheaders, and recipes (GetTradeSkillInfo). The retail version of WoW has headers for each expansion but the classic versions of WoW do not have these additional headers. The Blizzard API does not include a function to identify the expansion of each recipe.

To make this data available would require a massive amount of manually collected (and maintained) data which is not something I want to do.

There is, however, the custom group feature of Skillet-Classic which you can use to create your own recipe groupings (with headers). The recipe list in Skillet-Classic has left-click (with shift and ctrl) selection and right-click actions and similar to an editor.

Rather than creating custom groups for each expansion, most custom group users generate groups of favorites. If you have trouble getting started with custom groups, let me know.
