### ISSUE TITLE
Addon no longer showing profit from crafting?

### ISSUE THREAD

**Issue by nolailen** [b-morgan/Skillet-Classic#137]
Hello, after the update it seems the addon is no longer able to show the profit information it used to.  Can you please fix this?  I love your addon and would hate to have to learn TSM

**Comment by b-morgan** [comment]
The profit information is supplied by Skillet-Classic plugins and there are multiple plugins that could be the source. Each plugin gets information from an addon. The plugins are written so that if enabled the corresponding addon must also be enabled.

I can't fix anything unless I know what plugin (and therefore which addon) you are using for your profit information. Open Skillet-Classic options ("?" icon), select "Plugins" and see which are enabled. Verify that the corresponding addon is also enabled.
 
If you are still having problems after verifying that the addon has been updated for 3.4.1, let me know and I'll try to help.

**Comment by nolailen** [comment]
wow that fixed it i cant believe i didnt see those options, thanks so much
