### ISSUE TITLE
Shoppinglist Error

### ISSUE THREAD

**Issue by awsmChiprel** [b-morgan/Skillet-Classic#140]
1x Skillet-Classic/UI/ShoppingList.lua:1175: attempt to compare nil with string
[string "@Skillet-Classic/UI/ShoppingList.lua"]:1175: in function <Skillet-Classic/UI/ShoppingList.lua:1171>
[string "=[C]"]: in function `sort'
[string "@Skillet-Classic/UI/ShoppingList.lua"]:1171: in function `UpdateShoppingListWindow'
[string "@Skillet-Classic/UI/ShoppingList.lua"]:1307: in function `DisplayShoppingList'
[string "@Skillet-Classic/UI/ShoppingList.lua"]:678: in function `?'
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AtlasLootClassic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@AutoCombatLogger/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <.../AutoCombatLogger/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
a = <table> {
 player = "Asdf"
 count = 2
 id = 41806
 source = "?"
 value = 0
}
b = <table> {
 player = "Queercraft"
 count = 2
 id = 41809
 source = "?"
 value = 0
}
na = nil
nb = "Glacial Salmon"
(*temporary) = "Glacial Salmon"
(*temporary) = 41809
(*temporary) = "attempt to compare nil with string"

**Comment by b-morgan** [comment]
The Blizzard API function `GetItemInfo` requests information from the server if the data isn't available in the client and this takes time so the function returns nil. I'm going to guess this isn't very reproducible because the failure has already triggered the request so it will succeed when tried again.

You can try changing lines 1173-1174 in `...\Addons\Skillet-Classic\UI\ShoppingList.lua` to:
```
			na = GetItemInfo(a.id) or ""
			nb = GetItemInfo(b.id) or ""
```
which should eliminate the error.
