### ISSUE TITLE
[Bug][Classic 1.14.3] Error loading .lua file

### ISSUE THREAD

**Issue by apav** [b-morgan/Skillet-Classic#143]
Thank you for this great addon! I'm getting this error message pop up every time.

Error loading Interface\AddOns\Skillet-Classic\Libs\LibPeriodicTable-3.1-90603\LibPeriodicTable-3.1-TradeskillResultMats\LibPeriodicTable-3.1-TradeskillResultMats.lua

I checked and the file is there. The only difference is there is no "-90603" in the folder name, but even after adding that part I was getting the same error message, as well as more error messages. I've tried several versions all the way back to 1.14.2 and am still getting the same issue.

Thanks!

**Comment by b-morgan** [comment]
I cannot reproduce this error but I am confused because you are reporting the WoW Classic Era version number, not the Skillet-Classic version number. Please delete `...\Interface\Addons\Skillet-Classic`, download either [Skillet-Classic-1.67-classic](https://www.curseforge.com/wow/addons/skillet-classic/files/4424743) or [Skillet-Classic-1.68-alpha1-classic](https://www.curseforge.com/wow/addons/skillet-classic/files/4491411), verify the MD5 checksum, and install it. 

If you still have the error, then please disable all other addons and verify that the error still exists. Let me know the results and which version of Skillet-Classic you installed.

LibPeriodicTable is an ACE3 library. The way AC3 libraries load is complicated but the end result is that while multiple addons will contain the library code, only one copy will end up in memory and that should be the most recent version. The 90603 is the version number of the library.

**Comment by b-morgan** [comment]
I have no idea what is causing this error. Perhaps there is something in `...\World of Warcraft\_classic_era_\Logs\FrameXML.log` or one of the other logs.

**Comment by b-morgan** [comment]
LibPeriodicTable is an optional dependency so Skillet-Classic will run without it. If you want to eliminate the errors, edit the `Skillet-Classic.toc` file and comment (add `# ` to the beginning of lines 37-40:

```
# Libs\LibPeriodicTable-3.1\LibPeriodicTable-3.1.lua
# Libs\LibPeriodicTable-3.1\LibPeriodicTable-3.1-Tradeskill\LibPeriodicTable-3.1-Tradeskill.lua
# Libs\LibPeriodicTable-3.1\LibPeriodicTable-3.1-TradeskillResultMats\LibPeriodicTable-3.1-TradeskillResultMats.lua
# Libs\LibPeriodicTable-3.1\LibPeriodicTable-3.1-TradeskillLevels\LibPeriodicTable-3.1-TradeskillLevels.lua
```
