### ISSUE TITLE
Material list

### ISSUE THREAD

**Issue by Gunner-web** [b-morgan/Skillet-Classic#144]
When looking at items to craft, some items are used in so many things, (such as leather) that the display of the "Used for the following" list will run off the bottom of the screen.  Is there a way or option to maybe make that screen 2 columns wide?

![WoWScrnShot_042323_080458](https://user-images.githubusercontent.com/88938346/233841583-f6507afe-4e8f-49c8-b5f0-52ee280e53d4.jpg)

**Comment by b-morgan** [comment]
Skillet-Classic calls the Blizzard function [GameTooltip:SetTradeSkillItem(skillIndex)](https://wowpedia.fandom.com/wiki/API_GameTooltip_SetTradeSkillItem), adds a bit of its own information, and displays the result.

This "Used for the following" information being displayed is not generated by Skillet-Classic but by some other addon. You will have to figure out which addon that is because I don't recognize it.
