### ISSUE TITLE
Reagents occasionally show up blank

### ISSUE THREAD

**Issue by PaCozz** [b-morgan/Skillet-Classic#15]
The area where Reagents are supposed to be displayed occasionally shows up entirely empty. This seems to happen very randomly and i've not been able to find proper reprosteps for the issue. Could be some kind of item caching issue with the materials? Reloading UI or reopening the profession window clears the issue.

Steps to reproduce:
1. Launch wow BCC
2. Enable Skillet Addon
3. Log in to a character with Engineering/Tailoring
4. Open profession window and browse through some recipes
5. Observe a recipe with empty reagents window

Repro rate: 1/5. Bug observed on Engineering (Thorium Shells) and Tailoring (Glacial Wrists) and First Aid (Powerful Anti-Venom) and Cooking (Multiple recipes, eg. Baked Salmon)

Screenshot:
![WoWScrnShot_053121_191557](https://user-images.githubusercontent.com/78828265/120221047-6735a400-c246-11eb-8212-86cbb34b91c4.jpg)

**Comment by b-morgan** [comment]
This is a client / server synchronization issue and I'm not sure how to fix it. I've tried a bunch of things but they don't work 100% of the time and when they fail, they fail even more spectacularly than the current failure.

The workaround I use is to open and close all of my professions with action bar buttons just after I login. Then later, when I actually want to use Skillet-Classic, it usually has the correct information.

**Comment by b-morgan** [comment]
I'm assuming my workaround is working for you. If not, please reopen this issue with details.

**Comment by stijnherreman** [comment]
I'm having a similar issue with Tailoring, could it be from the same cause? Sometimes the reagents list only shows Bolt of Runecloth, but other reagents like Rugged Leather and Rune Thread are missing. Closing and reopening the profession appears to fix it.

**Comment by b-morgan** [comment]
Skillet-Classic-1.28-alpha1 contains a rewrite of the frame opening code in an attempt to correct this behavior. Since it is intermittent, I would like you to please enable Skillet-Classic debugging using the following commands (use /skillet debugstatus to show the current state):

/skillet warnlog on
/skillet debuglogging on
/skillet tracelog on
/skillet tabledump

This will send the debug output to the current character specific saved variables file. The size of the output buffer is limited and only the most recent output is saved.

Should you discover blank or missing reagents or see the chat message "No headers, try again" please close the Skillet-Classic frame, logoff, and zip and upload the character specific saved variable file, Skillet-Classic.lua here. Use "/skillet cleardebuglog" when you next login to remove what you have uploaded. The chat message "No headers, try again" may appear multiple times and I suspect that it may not be relevant in this current code rewrite. I do, however, want to study the debug log when this happens to see if I can discover a pattern that can be coded for.

There is a strong possibility that this isn't the final version of this code so check back often to see if a new alpha build is available.
