### ISSUE TITLE
Skillet 1.74 update scrollbar broken

### ISSUE THREAD

**Issue by Velarax** [b-morgan/Skillet-Classic#151]
Unable to scroll through recipes.  Scroll button on bar slides, but does not affect skill list window.

**Comment by b-morgan** [comment]
This was an issue in 1.72 when 3.4.2 was released but was fixed in 1.73 and is still fixed in 1.74 (I just tested it on both Wrath and Classic Era). Please verify that your installation of 1.74 was successful. If necessary, download manually, verify the MD5 checksum, and install manually.

If it still fails, I need more information starting with which version of WoW. I'll provide further instructions on enabling Skillet-Classic's debug output if necessary.

**Comment by Velarax** [comment]
Thank you for your very prompt response.  The issue is that curse is pushing 1.72 mislabeled for wrath classic as 1.74.  I had to check the toc.  I did manually download 1.74 but you might want to look into the issue on Curse.  Many thanks

**Comment by b-morgan** [comment]
I would need to know exactly how you are using Curse so I can try and duplicate the issue. Since I'm developing Skillet-Classic I almost always download and install manually to verify that what I have packaged and uploaded is correct.

**Comment by Velarax** [comment]
I merely search for addons by latest update.  Curse provides links to Skillet, Skillet Classic for Wrath and Skillet classic.

I usually click on the addon link, then scroll down to see the latest revision.   Usually the link is accurate.  In this case, the link for Wrath 1.74 links to 1.72 instead.

So, clicking on the "Files" tab, I located the actual file and downloaded it.  I checked the toc to ensure it was 1.74.  Also I can confirm this did fix the problem, so thank you again.
