### ISSUE TITLE
There seems to be an issue with TSM

### ISSUE THREAD

**Issue by frogbound** [b-morgan/Skillet-Classic#159]
Hello!

Thank you for this amazing addon btw! I really helps a lot when trying to offer some profession services!

I have however encountered an error where I can't open my enchanting window anymore when TSM is running.
It all started when I checked the "Hide Blizzard Frame" option while using TSM.
Skillet shows a short message in chat saying: "There is an issue with TSM" and it won't open the enchanting window anymore until I disable either skillet or TSM.

I was encountering this issue with the latest release version but also with the latest alpha release version 1.81-alpha2

https://i.imgur.com/xHCM4O7.png

**Comment by b-morgan** [comment]
Skillet-Classic and Trade Skill Master have always had a tremulous relationship because TSM believes it is the only tradeskill addon and their developers have refused to work with me on a mutually compatible relationship. I have tried my best but there's only so much I can do without some cooperation.

You didn't say which version of World of Warcraft but I'm guessing Classic Era or Season of Discovery. 

I will quote the Skillet-Classic description (under Compatibility):
"Skillet-Classic can be used with TSM for all professions except Enchanting. TSM Crafting UI must be set to native ('TSM4') mode. For Enchanting, use the TSM Crafting UI or disable TSM."

If your issue is on SoD, then I don't have an enchanter I can test with. If you can, please verify that regular Classic Era realms also have the issue and I can see if I can recreate it and then attempt to do something about it.
