### ISSUE TITLE
Missing ingredients for some alchemy recipes

### ISSUE THREAD

**Issue by danez** [b-morgan/Skillet-Classic#165]
In wow classic era, some alchemy recipes have missing ingredients.

Examples:
Missing Ghost Mushroom and Crystal Vial in both recipes:
<img width="798" alt="Screenshot 2024-02-28 at 11 25 29" src="https://github.com/b-morgan/Skillet-Classic/assets/231804/75f2700e-7347-427f-b6b7-7ffa341ae030">

<img width="915" alt="Screenshot 2024-02-28 at 11 25 36" src="https://github.com/b-morgan/Skillet-Classic/assets/231804/467222bd-80b6-44d1-9ba1-05adc9f4d6ee">

I tried looking through the code, but couldn't find out where the data is coming from.

**Comment by b-morgan** [comment]
Skillet-Classic gets the recipe reagents through the Blizzard API (running on the client). The Blizzard API gets its data from the server. Unfortunately, there's no Blizzard API function to verify that the client has all the data from the server. Closing and reopening Skillet-Classic usually fixes this issue (and then it will be good for the rest of the session).

Since the Blizzard TradeSkill UI doesn't seem to have this problem, I'm guessing there is an internal, undocumented, can't be called from addons function that the Blizzard UI uses.

**Comment by b-morgan** [comment]
Skillet-Classic-1.83-alpha5 contains code that should detect this issue. It does not yet contain code that can recover so you will still have to close and reopen Skillet-Classic.

**Comment by b-morgan** [comment]
Reopen this issue (or start a new one) if this is still a problem.
