### ISSUE TITLE
Glyph of Deathcoil (lock) - not removing from craft queue once crafted

### ISSUE THREAD

**Issue by Esc1972** [b-morgan/Skillet-Classic#176]
Hi,

Hopefully this ticket is more useful than my last one, no major issues and a great addon so thank you first of all.

One minor issue with Glyph of Death Coil (Warlock one), when i craft this and i am using the crafting queue and clicking process to craft the next glyph, after i've ran through and selected all that i want to craft, Glyph of Deathcoil (warlock) remains in the queue even when crafted. This means the addon creates multiple of these glyphs (1 each time i press process), unless i manually remove it from the queue.

The display is also unusual, displaying a number in brackets following the name, but perhaps this because it shares the name with the DK glyph. The DK glyph does not have this issue

![image](https://github.com/b-morgan/Skillet-Classic/assets/169260836/7724ebc9-42f0-4353-a5a4-ff60adeb7992)

Let me know if there is any more data or info i can provide
Thanks

**Comment by b-morgan** [comment]
Skillet-Classic uses the skillName as the recipeID because the actual recipeID was not available when Skillet-Classic was initially developed. It does attempt to create a unique recipeID when there are duplicate skillNames and that's what the number represents.

I have replicated the issue but I think this is going to take a while to fix.

**Comment by Esc1972** [comment]
All good, it's very minor issue

**Comment by b-morgan** [comment]
I was able to find a simple fix which is included in [Skillet-Classic-1.92-alpha1](https://legacy.curseforge.com/wow/addons/skillet-classic/files/5403653).
