### ISSUE TITLE
Profession Linking does not work

### ISSUE THREAD

**Issue by Dejoule** [b-morgan/Skillet-Classic#20]
TBC has profession linking, or at the very least the ability to link specific recipes that you can craft from your profession window by shift-clicking on them. This is not functioning at present with skillet.

**Comment by b-morgan** [comment]
The Skillet-Classic recipe list has alternate uses for modified clicking due to its ability to create and manage custom recipe lists. Instead of shift-left-click to generate a recipe link, you use right-click and select (left-click) Link Recipe.

I'm not aware of any full profession linking but if it exists, please provide me with the details.

In addition to the recipe link, Skillet-Classic can generate links from the detail frame. Shift-click the item icon to link the item, Alt-click the item icon to link the reagents with counts. 

The reagent icons can be shift-clicked to link and if the item is craftable (by you), then left-click will take you to that recipe and the back icon (above the item icon) will take you back. Note that opening and closing all of your professions may be needed for this to work (this causes the client to download all the profession data from the server).

The shift-left-click in the recipe list does the following. First left-click a recipe, then shift-left-click a couple of recipes away from the one you clicked. This will select all the recipes in between or shift-click on the first recipe, and ctrl-left-click on other recipes to select multiple non-adjacent recipes. Now right-click on a selected recipe and you have choices.

The arrow next to the Grouping dropdown starts you on the path to creating custom groups, the above recipe selection method is how you populate those custom groups (with cut, copy, and paste). Skillet-Classic implemented Favorites way before Blizzard Retail and can create multiple "favorite lists" unlike Blizzard's single list.
