### ISSUE TITLE
No filters are usable

### ISSUE THREAD

**Issue by addohm** [b-morgan/Skillet-Classic#22]
The one main feature I really want to be able to use is filtering by "inventory slot" but its not clickable in the UI.  
![image](https://user-images.githubusercontent.com/25333107/121724193-87baf500-cab5-11eb-983c-7919893073d1.png)

**Comment by b-morgan** [comment]
This is an unfortunate side-effect of Blizzard's decision to make Enchanting a Craft instead of a Trade Skill. If you examine the Blizzard Enchanting UI you will notice there are no dropdowns for subClass and InvSlot. 

Skillet-Classic obtains the values for these filters from the Blizzard API function **GetItemInfo** which returns nothing for enchanting items. 

If there is an issue here, it's that Skillet-Classic doesn't disable the Filter dropdown when Enchanting is the profession.

However, all is not completely lost because Skillet-Classic has Custom Groups. For example, in the Search box, type "Chest". Click on the first enchant and shift-click the last enchant, right-click and select Copy. Now click the arrow next to Grouping and select New. In the empty recipe space, right-click and select Paste. Click the arrow next to Grouping and select Rename. Change "Custom" to "Chest". Return to the "Blizzard" or "Flat" group and repeat using "Bracer".

You can select multiple recipes that are not adjacent by using click on the first and ctrl-click on each additional. Recipes can be in multiple custom groups so you can reorganize Enchanting however you desire.

Play with this for a while and then ask questions. I'm not an expert on this part of the Skillet-Classic code because I didn't write it. I should find someone clever enough figure it out and do a video or someone patient enough to capture dozens of screenshots and write a wiki.
