### ISSUE TITLE
Shift+Click a spell won't produce a link to the chat window

### ISSUE THREAD

**Issue by Zereges** [b-morgan/Skillet-Classic#64]
Shift clicking on spell in profession window in classic trade skill window produces a link in the chat that is clickable. Doing so in Skillet doesn't produce any sort of a link.

**Comment by b-morgan** [comment]
This is by design (see below). To link a recipe to chat, right-click on a recipe in the list and choose Link Recipe. Shift-click on the item icon in the details to link the item, and alt-click on the item icon to link all the reagents with counts. Shift-click on each reagent to link it (without a count).

Shift-Click on a single recipe doesn't appear to do anything but if you click on one recipe and then shift-click on a second recipe you will see that all the recipes between the first recipe and the second recipe are highlighted. Ctrl-click will allow selection of non-adjacent recipes. Once you have a selection of recipes, the rest of the right-click menu comes into play.

**Comment by Zereges** [comment]
Ah, I see. Maybe update a description of the addon to reflect that :)

**Comment by b-morgan** [comment]
Done.
