### ISSUE TITLE
tbc enchanting voidsphere  atr buyout not read, so incorrect profit percentage

### ISSUE THREAD

**Issue by chorp-cpu** [b-morgan/Skillet-Classic#66]
tbc skillet v 1.42
enchanting voidsphere  shows no atr buyout, so the profit percentage is just minus the cost. auctionator does have data data for the voidsphere and mousing over one in the bags shows an auction value.

**Comment by b-morgan** [comment]
I'm not sure I understand the issue. Skillet-Classic interfaces with Auctionator (ATR) through its published API. If that API isn't providing the correct data, there is nothing Skillet-Classic can do about it.

Furthermore, the data that Auctionator does supply is collected by scanning the AH making it unique to each account.

If you think the Skillet-Classic Auctionator plugin should be doing something different, please provide enough detail so I figure out what should be done.

**Comment by chorp-cpu** [comment]
I dont know how to make it clearer.

for voidsphere under enchanting:
ATR Buyout:  0c
cost: 21g80s0c
Profit: -21g80s0c
Profit percentage: -100%

yet when i mouse over a voidsphere in bags i get:
auction 44g70s0c

obviously auctionator has voidsphere auction price in its database, but skillet cannot read it and its reporting 0.

skillet should be saying 
ATR Buyout:  44g70s0c
cost: 21g80s0c
Profit: 22g9s0c
Profit percentage: 195%

**Comment by b-morgan** [comment]
I believe the bug is with Auctionator, not Skillet-Classic. The code (in `...\Addons\Skillet-Classic\Plugins\Auctionator.lua` lines 329-336 is pretty simple so I'm not sure how Skillet-Classic can screw it up. 
```
			local value
			if Atr_GetAuctionBuyout then
				value = (Atr_GetAuctionBuyout(id) or 0) * needed
			elseif Auctionator and Auctionator.API.v1.GetAuctionPriceByItemID then
				value = (Auctionator.API.v1.GetAuctionPriceByItemID(addonName, id) or 0) * needed
			else
				value = 0
			end
```
There are two versions of Auctionator for Burning Crusade Classic which is why there are two different calls. You need to ask Auctionator why there is a value in the tooltip but (pick the right function above) doesn't return the same value.

Perhaps Skillet-Classic isn't using the right function call but unless someone more knowledgeable than myself tells me the right function call, there is nothing I can do.

According to [Wowhead](https://tbc.wowhead.com/item=22459/void-sphere), a Void Sphere is item 22459 and 

`/dump Auctionator.API.v1.GetAuctionPriceByItemID("Skillet-Classic", 22459)` on my server returns 394000 (39g40s0c). What does it return on yours?

**Comment by chorp-cpu** [comment]
/dump returns:
[1]=489000
that lua edit fixed it.
atr buyout 48g
cost 19g
profit 28g
percentage 144%

**Comment by b-morgan** [comment]
Thanks, I'll add that line in the next build.
