### ISSUE TITLE
UI Not Opening for Jewel Crafting

### ISSUE THREAD

**Issue by gaellin** [b-morgan/Skillet-Classic#68]
Skillet UI does not open for Jewel Crafting, works fine for Enchanting.

**Comment by b-morgan** [comment]
I'm not sure what the problem is, but it works for me:

![JC](https://user-images.githubusercontent.com/1547854/151677724-9493c2a9-2ec8-4d7e-8712-98a8644c2179.jpg)

To start, verify that the issue still exists when all other addons have been disabled. If that fixes the issue, then enable your other addons a few at a time (I use a binary algorithm, half at a time, then a quarter, etc.). If it fails when Skillet-Classic is the only addon, I will need your global saved variables file, Skillet-Classic.lua, and we may need to enable Skillet-Classic's debugging.

GitHub won't allow files with a .lua attachment to be uploaded so either zip it first, or add a .txt extension.

**Comment by gaellin** [comment]
If I open it through enchanting then click on JC button at top of skillet window JC window opens.  If I try and open JC from actionbar, the blizzard window opens.  Will try with all addons disabled.

**Comment by b-morgan** [comment]
Are you using the "shift" key when you click the action button for JC? If so, type "/skillet nomodkeys" and that should fix it.

**Comment by gaellin** [comment]
I am using a macro as follows:

#showtooltip
/use [nomod]Disenchant
/use [mod:alt]Prospecting
/use [mod:ctrl]Enchanting
/use [mod:shift]Jewelcrafting

So yes I am indeed using the shift key to open skillet for JCing.  Trying your suggestion right now.  Worked Perfectly, ty.
