### ISSUE TITLE
Feature Request: Cancelform when crafting

### ISSUE THREAD

**Issue by Nihlo** [b-morgan/Skillet-Classic#72]
Hey, thanks for your work, a great addon. Could you add a cancelform function when you use the crafting button ? Would be great for druids/shamans out there.

I tried:
https://www.curseforge.com/wow/addons/cancelformforcrafting
but it only works with the default blizzard window.

Thanks

**Comment by b-morgan** [comment]
Skillet-Classic (and Skillet) are trade skill addons. Aside from capturing the player class, there is no class-specific code anywhere in the addon, and I don't believe it is appropriate to add any (especially since I don't have a Druid character).

In addition, Skillet-Classic adds the ability to queue recipes to be processed at a more appropriate time. Simple button replacement as used by this addon would probably not work.

Since Skillet-Classic already has some support for third-party addon interaction (some documentation in `...\Interface\Addons\Skillet-Classic\ThirdPartyHooks.lua`), if the author of cancelformforcrafting wants to support Skillet-Classic then I would be willing to provide some support. Have them contact me through this issue.

Without any code modifications, there is already a function to add a button to Skillet-Classic's frame, `Skillet:AddButtonToTradeskillWindow(button)`. 

I think the most appropriate place for additional code would be in the function `Skillet:ProcessQueue(altMode)` located in `...\Interface\Addons\Skillet-Classic\SkilletQueue.lua`. I would be willing to add a documented hook to this function.

**Comment by b-morgan** [comment]
The API call to cancel a form is protected and cannot be called directly. The code for the buttons in Skillet-Classic are more complicated than those of the default Blizzard UI so I'm not inclined to make any changes to support this feature.
