### ISSUE TITLE
Skillet no longer showing craftable counts unless all components are already in my bags

### ISSUE THREAD

**Issue by red13dotnet** [b-morgan/Skillet-Classic#77]
Skillet is no longer showing craftable counts unless all components are already in my bags.
Attached screenshot showing counts for components in bank are sufficient to produce but count is not reflected on the recipe list pane.
All filter options are set to ON.  

Have already attempted savedvariable reset and this screenshot was taken with no other addons loaded
![skillet_bug](https://user-images.githubusercontent.com/6653726/185690884-e69e0d37-db5d-49c2-a68c-a8787addbe55.jpg)
.

**Comment by red13dotnet** [comment]
More info, its only one character having the problem.  I have 3 others working normally.
I have additionally tried using the reset profile function, and also the copy profile function to copy from a working characters profile.
No change in behavior.

**Comment by b-morgan** [comment]
We will probably need to enable debugging to get to the bottom of this but first, copy the global saved variables file Skillet-Classic.lua and the four per character saved variables files renaming each one from Skillet-Classic.lua to <character name>.lua, zip them and attach here. I'll take a look at them and then post instructions on enabling debugging if we need to go that route.

**Comment by red13dotnet** [comment]
Double checked and it actually does seem to be affecting all 4 characters.
Requested files attached
[skillet_classic_issue_77.zip](https://github.com/b-morgan/Skillet-Classic/files/9385019/skillet_classic_issue_77.zip)

**Comment by b-morgan** [comment]
You say "Skillet is no longer" and I need to ask, when did Skillet-Classic ever work this way? Retail WoW (i.e. Skillet) allows crafting using items in the bank, Classic WoW doesn't.

**Comment by red13dotnet** [comment]
Yeah, i think you hit the nail on the head.  I really could have sworn you could queue up items from counts based on bag and bank contents and then use that to pull the items out of your bank when you visited the bank.   I must have misremebered after starting classic again.  Sorry for the trouble.

**Comment by b-morgan** [comment]
I think the best Skillet-Classic could do would be to add an option similar to "Use guildbank as another alt", i.e. "Use bank as another alt".

**Comment by red13dotnet** [comment]
I would love to try it, thank you!

**Comment by b-morgan** [comment]
[Skillet-Classic-1.47-alpha2](https://www.curseforge.com/wow/addons/skillet-classic/files/3942574) has a new option to use the character's bank as another alt. Note that all reagents must be available in the bank, i.e. You can't have some in inventory and some in the bank.

Let me know if this is useful or if you find any bugs.

**Comment by b-morgan** [comment]
Opps... Use alpha3 instead.

**Comment by red13dotnet** [comment]
I will give this a try and let you know.

Thanks again!

**Comment by red13dotnet** [comment]
That build is certainly way closer to what I was thinking and I havent noticed any errors so far.

I do want to verify this is expected behavior:  
Craftable counts for bank contents do not reflect craftable reagents whose components are in the bank.
Example: Tailoring  Linen Bag, If I have a stack of linen in my bank, then the bank(alt) number of craftable bags remains zero but the craftable bank(alt) number for crafting bolts of linen cloth is correct.
If that same stack of linen is moved to inventory, the craftable by crafting reagents reflects the correct number.  
However if I then turned the linen into bolts, and put those bolts in my bank, then the craftable bank(alt) count is correct.

**Comment by b-morgan** [comment]
I believe your example is correct. I didn't change the calculation of the craftable count. The alts count only checks for the actual reagents. It does not consider reagents that could be used to craft the reagent needed.

The "magic" happens when you queue, for example, a Linen Bag when you don't have all the materials in your inventory. The shopping list is now populated with any missing reagents including the reagents required to craft reagents. When you visit your bank it can pull what it needs into your inventory. When you visit merchants that sell needed reagents, Skillet-Classic will buy them for you, and if you switch to alts that have reagents in their bank, it can pull them into the alts inventory so you can send them via mail to the crafter. You can open the shopping list with the command "/skillet shoppinglist".

There are many addons that will collect information about the contents of your alt's bags and banks and add that information to the tooltips that Skillet-Classic displays. Skillet-Classic knows some your alt's inventory but only if you've used Skillet-Classic on that toon. I use Altoholic and tooltips from the shopping list to see who has what.

**Comment by red13dotnet** [comment]
Thank you, I think this will work just fine.
I appreciate the work you've done.
