### ISSUE TITLE
Can't open crafting windows, Conflict with TSM

### ISSUE THREAD

**Issue by ByucknahTheRed** [b-morgan/Skillet-Classic#8]
So with Skillet BCC whenever I try to open my tailoring profession I get a message in chat saying "Skillet-Classic: Conflict with the addon TradeSkillMaster" and nothing happens, except for Enchanting which opens jut fine. I can not open my tailoring however for whatever reason.

I read the main page and it's odd because the main page suggests that Enchanting should not work when Enchanting is the only one that will open right now XD

**Comment by b-morgan** [comment]
Skillet-Classic and TradeSkillMaster (TSM) have, at best, a tumultuous relationship. I have attempted to work with the TSM developers so that the two addons can co-exist, but they have refused to acknowledge Skillet-Classic's existence. I have done what I can but cannot guarantee that the two addons will work when both are enabled in the future.

TradeSkillMaster (TSM) has two modes, TSM4 and WOW UI. When TSM is in WOW UI mode, it does something to the Blizzard API functions that Skillet-Classic needs to function. If TSM is in TSM4 mode, then Skillet-Classic gets the data it needs and also changes the Skillet-Classic frame(s) so that it can compete with TSM.

The message you are seeing in chat means you have the wrong mode selected in TSM which you can change by clicking the button at the top of the Blizzard TradeSkill frame.

In WoW Classic and Burning Crusade Classic, Enchanting is not a trade skill, it is a craft. Skillet-Classic has a lot of code behind the scenes to make Enchanting look like the rest of the professions and with the right options set, can even queue enchants so that materials can be obtained through the Skillet-Classic shopping list. I'll have to transfer a character with Enchanting over to BCC so I can see what happens when TSM is in each of its modes.

**Comment by b-morgan** [comment]
The comments in the [Description of Skillet-Classic](https://www.curseforge.com/wow/addons/skillet-classic) are correct. With TSM in its native (TSM4) mode, Skillet-Classic will work with all professions that use the Blizzard tradeskill UI. 

On my system, Enchanting, which uses the Blizzard craft UI, will not work when TSM is enabled (in any mode). The fact that it works/worked for you is a mystery to me and not something I wish to pursue.
