### ISSUE TITLE
Linking Profession

### ISSUE THREAD

**Issue by Lugnaut** [b-morgan/Skillet-Classic#80]
There is no button to link professions like the blizzard frame allows. Is removing this functionality intentional?

**Comment by b-morgan** [comment]
The functionality has not been removed, it has been shift-click the profession icon since the addon was first released. The red box in the image below. Note that you can only link the profession that is currently displayed. Click an icon to change the displayed profession then shift-click to link it. 

You will have to open each profession once using an action bar button before the buttons in the Skillet-Classic frame will function. This restriction is to work around a Blizzard bug. I'll find out sometime in the future (when the rest of the issues are resolved) if they have fixed their bug.

![image](https://user-images.githubusercontent.com/1547854/188005362-ec1f76ef-f292-4f50-9ee1-aefd7bb8e875.png)

**Comment by Lugnaut** [comment]
Ah I didn't see the functionality listed anywhere. Thanks for the heads up.
