### ISSUE TITLE
Enchanting search bugged

### ISSUE THREAD

**Issue by Shioban2293** [b-morgan/Skillet-Classic#86]
When i search for an enchant in the enchanting window and go as far as f/i "agil" (without the quotes) it shows nothing anymore, i.o.w. i can't use the fast search like this anymore and need to scroll through my enchanting formulas.

**Comment by b-morgan** [comment]
It is not just enchanting. The search is FUBAR for all professions. I'm looking into it.

**Comment by b-morgan** [comment]
This should be fixed in [Skillet-Classic-1.48-alpha3](https://www.curseforge.com/wow/addons/skillet-classic/files/3969833).

Note that if the first character of the search string is "!" then only the recipe names are searched. 

If the first character is not "!" then the recipe name and the created item tooltip is searched. In the case of enchants, the enchant description is used instead of the item tooltip. In addition, if the Skillet-Classic option "search_includes_reagents" is set, then the names of each reagent are also added to the search.

**Comment by Raulfin** [comment]
Most things i've tried seem to work, but searching Ring has a lot of extra stuff included. ring doesn't appear in the tooltip or regent of any of the extra items. !ring is just the 2 ring enchants though.
![WowClassic_rxJiNqYAHb](https://user-images.githubusercontent.com/7994405/189171489-6d4286a9-b130-4970-a062-ad7747415484.png)

**Comment by Raulfin** [comment]
### GlimmeRING Shard

**Comment by b-morgan** [comment]
Note that if you search for "!ring" you will only find the two recipes. Alternatively, you could uncheck the Skillet-Classic option "Include Reagents in Search" if you don't want to keep typing the "!".
