### ISSUE TITLE
recipie id chat spam

### ISSUE THREAD

**Issue by Raulfin** [b-morgan/Skillet-Classic#90]
Just noticed that when i open prof skillet will print crafting recipie ids to chat log. Was using 1.47 and updated to 1.48B1 but is still the same. Is on all my toons, tried reloading, restarting client, reinstalling and deleting Skillet-Classic.lua.  Didn't make any changes to any setting on any addon, it just started doing this an hr or 2 ago .

**Comment by Raulfin** [comment]
![WowClassic_HLsB91USd4](https://user-images.githubusercontent.com/7994405/188728784-73e029a9-d31e-48fb-9de7-18aeb8a17852.png)

**Comment by b-morgan** [comment]
I'm very confused. Where did you get the addon? I've downloaded from [Curseforge ](https://www.curseforge.com/wow/addons/skillet-classic/files/3971239), from [Github](https://github.com/b-morgan/Skillet-Classic/releases/download/1.48-beta1/Skillet-Classic-1.48-beta1-wrath.zip), and from [WoWInterface](https://www.wowinterface.com/downloads/dlfile3754/Skillet-Classic-1.48-beta1-wrath.zip?1662479572). All three packages contain the same code and none of them do this on my system.

When I search the Skillet-Classic sources for the values mentioned, I see a similar set of itemIDs in SkillLevelData.lua but the data in that file is not in the format of your output.

Can you please post the output from chat after typing `/skillet debugstatus`.

**Comment by Raulfin** [comment]
from the curse app

**Comment by Raulfin** [comment]
[23:08:34] WarnShow= nil, WarnLog= true 
[23:08:34] DebugShow= nil, DebugLogging= nil, DebugLevel= nil 
[23:08:34] TraceShow= nil, TraceLog= nil 
[23:08:34] ProfileShow= nil 
[23:08:34] TableDump= nil 
[23:08:34] LogLevel= nil 
[23:08:34] #DebugLog= 368 (4000) 
[23:08:34] #DebugProfile= 0 (2000)

**Comment by b-morgan** [comment]
Please go to [[download](https://www.curseforge.com/wow/addons/skillet-classic/files)](https://www.curseforge.com/wow/addons/skillet-classic/files) and open Skillet-Classic-1.48-beta2. Click the Download button and also copy the MD5 string. If you don't have an MD5 sum utility, download [https://www.winmd5.com/?rid=winmd5](https://www.winmd5.com/?rid=winmd5). The computed MD5 sum should match the one on Curseforge.

If it does, delete `...\World of Warcraft\_classic_\Interface\AddOns\Skillet-Classic and unzip the downloaded file into `D:\World of Warcraft\_classic_\Interface\AddOns`.

I hope this issue goes away after this because if it doesn't, I have no idea what is going on.

**Comment by Raulfin** [comment]
doesn;t match
is 
ff0d7f7e4c8a76a46655d17b84b3ce61
after dl

**Comment by Raulfin** [comment]
It looks like it's coming from a different addon. Yours is the only one i have that has anything to do with profs so i kinda skiped the turn it off and back on step without thinking, my bad.

**Comment by b-morgan** [comment]
So I'm closing this issue as resolved. If I'm wrong, open it again.
